config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  root 'static_pages#home'
  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :clothes
  resources :users
  # root 'application#welcome'
  get '/signup', to: 'users#new'
  get '/uploadclothes', to: 'clothes#new'
  get '/generate', to: 'users#generate'
  get '/generate_again', to: 'users#generate_again', as: :generate_again
  get '/closet', to: 'sessions#show'
  get '/laundry', to: 'users#laundry'
  patch '/ootd', to: 'users#ootd'
  patch '/wash', to: 'users#wash'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  before_save { email.downcase! }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: true

  has_secure_password
  validates :password, presence: true, length: { minimum: 7 }
  has_many :clothes

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  protect_from_forgery except: :generate_again
  require 'Weather'
  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @user = User.find params[:id]
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        reset_session #-- 8:56
        log_in @user #-- 8:56
        format.html { redirect_to @user }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def generate_again
    @new_clothe = Clothe.where.not(id: params[:pastid]).where(user_id: params[:userid], quadrant: params[:quad],
                                                              clothing_category: params[:category], occasion: params[:occ], clean: true).sample
    if params[:quad] == 'Top' && (params[:category] == 'Winter-Coat' || params[:category] == 'Fall/Spring-Jacket')
      @random_top2 = @new_clothe
    elsif params[:quad] == 'Top'
      @random_top = @new_clothe
    elsif params[:quad] == 'Bottom'
      @random_bottom = @new_clothe
    elsif params[:quad] == 'Socks'
      @random_socks = @new_clothe
    elsif params[:quad] == 'Shoes'
      @random_shoes = @new_clothe
    elsif params[:quad] == 'Accessory'
      @random_accessory = @new_clothe
    end
    respond_to do |format|
      format.js {}
    end
  end

  def generate
    ip_address = if Rails.env.production?
                   request.remote_ip
                 else
                   Net::HTTP.get(URI.parse('http://checkip.amazonaws.com/')).squish
                 end
    @occasion = params[:occasion]
    @occasion = 'Casual' if @occasion.nil?
    @user_id = params[:user_id]
    @clothes = Clothe.all
    clothing = Weather.new(ip_address, @user_id, @occasion)
    @output = clothing.get_output
    @random_top = clothing.get_top
    @random_top2 = clothing.get_top2
    @random_bottom = clothing.get_bottom
    @random_socks = clothing.get_socks
    @random_shoes = clothing.get_shoes
    @random_accessory = clothing.get_accessory

    @ootd = { top: @random_top, jacket: @random_top2, bottom: @random_bottom, socks: @random_socks,
              shoes: @random_shoes }
  end

  def ootd
    @top = params[:top]
    @jacket = params[:top2]
    @bottom = params[:bottom]
    @socks = params[:socks]
    @shoes = params[:shoes]

    unless @top.nil?
      @top = Clothe.where(id: @top)
      @top.update(clean: false)
    end

    unless @top2.nil?
      @top2 = Clothe.where(id: @top2)
      @top2.update(clean: false)
    end

    unless @bottom.nil?
      @bottom = Clothe.where(id: @bottom)
      @bottom.update(clean: false)
    end

    unless @socks.nil?
      @socks = Clothe.where(id: @socks)
      @socks.update(clean: false)
    end

    unless @shoes.nil?
      @shoes = Clothe.where(id: @shoes)
      @shoes.update(clean: false)
    end
  end

  def laundry
    @user = User.find(params[:user_id])
    @user_clothes = Clothe.where(user_id: @user.id, clean: false)
  end

  def wash
    @user = User.find(session[:user_id])
    @used_clothes = Clothe.where(user_id: @user.id, clean: false)

    @used_clothes.each do |clothing|
      clothing.update(clean: true)
    end

    redirect_to @user
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :email, :password, :quadrant)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_dirty_clothes.html.erb
<div class="myGallery">
<% @user.clothes.each do |specs| %>
  <%if specs.quadrant==quad && specs.clean == false%>
     <div class="item">
     <%= link_to edit_clothe_path(specs) do %>
      <%= image_tag(specs.photo) if specs.photo.attached? %>
      <% end %>
      <span class="caption"> <%= specs.quadrant %>
        <%= specs.clothing_category %>
        <%= specs.color %>
        <%= specs.occasion %></span>
      </div>
  <% end %>  
<% end %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_my_partial.html.erb
<div class="myGallery">
<% @user.clothes.each do |specs| %>
  <%if specs.quadrant==quad%>
     <div class="item">
     <%= link_to edit_clothe_path(specs) do %>
      <%= image_tag(specs.photo, style:"border-radius:50%;") if specs.photo.attached? %>
      <% end %>
      <span class="caption"> <%= specs.quadrant %>
        <%= specs.clothing_category %>
        <%= specs.occasion %></span>
      </div>
  <% end %>  
<% end %>
</div>

app/views/users/dirty.html.erb
<h3> Hi <%= @user.name%> your clothes need washing! </h3>
<table>
	<thead>
		<tr>
			<th> Dirty clothes </th>
		</tr>
	</thead>

	<tbody>
		<% @user_clothes.each do |item| %>
			<tr>
				<td> <%= image_tag(item.photo, width: 200, heigh: 200) if item.photo.attached? %></td>
			</tr>
		<% end%>
	</tbody>
</table>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/generate.html.erb

<head>
<meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<%= render "layouts/header" %>


<div class="row">

  <div class="column left" style="width: 25%; margin-left: 5%;">
  <div class="row center padding-above">
    <h2 class="text-with-line"><span>Weather</span></h2>
    <%@icon= @output['current']['weather'][0]["icon"]%>
    <div class="weathergrid">
  <div class="top-left"><p style="text-align:center;"><%= image_tag "http://openweathermap.org/img/wn/#{@icon}@2x.png"%></p></div>
  <div class="bottom-left"><p style="text-align:center;"><%= @output['current']['weather'][0]["description"].capitalize%></p></div>
  <div class="top-right"><b><p style="text-align:center; font-size:40px"><%= @output['current']['temp'].truncate%>°F</p></b></div>
  <div class="bottom-right"><p style="text-align:center; font-size:13px">Feels like <%= @output['current']['feels_like'].truncate%>°F</p></div>
</div>
    <%if !@output['alerts'].nil?%>
     <p style="color:red"><b>ALERT: <%=@output['alerts'][0]["event"].upcase%> </b></p>
     <%end%>
    </div>
    <div class="row center padding-below">
      <h2 class="text-with-line"><span>Occasion</span></h2>
      <%= link_to "Casual",generate_path(:user_id => @user_id,:occasion => "Casual"),class: "btn green-btn divide"%>
      <%= link_to "Business-Casual",generate_path(:user_id => @user_id,:occasion => "Business-Casual"),class: "btn green-btn"%>
    </div>
     <div class="row center">
    <h2 class="text-with-line" ><span>Pick Outfit</span></h2>
      <%= button_to "Wear",ootd_path(@ootd),:method => :patch, data: { confirm: 'This outfit has been added to your laundry!' }, class: "btn green-btn divide"%>
      </div>
    <%if %w[Thunderstorm Drizzle Rain].include?(@output['current']['weather'][0]['main']) || !@random_accessory.nil? && @random_accessory.photo.attached? %>
    <div>
    <h2 class="text-with-line padding-below"><span>Accessory</span></h2>
    </div>
    <div style="display:flex;">
    <%if !@random_accessory.nil? && @random_accessory.photo.attached?%>
      <%= link_to image_tag(@random_accessory.photo, width: 260,height: 260),generate_again_path(:quad=>@random_accessory.quadrant,:category=>@random_accessory.clothing_category,:pastid => @random_accessory.id, :userid=>@random_accessory.user_id,:occ =>@random_accessory.occasion),id:"accessory",remote: true%>
      <%end%>
      <%if %w[Thunderstorm Drizzle Rain].include?(@output['current']['weather'][0]['main'])%>
     <%= image_tag("blackumbrella.jpg", width: 260,height: 260)%>
    <%end%>
       </div>
      <%end%> 
   
  </div>

  <div class="column right">
    <div class="outfit center" style="text-align: center;">
      <h1 style="margin-top: 30px;"> Your outfit for the day is: </h1>
      <div>
      <%if !@random_top.nil? && @random_top.photo.attached? %>
      <%= link_to image_tag(@random_top.photo, width: 260,height: 260),generate_again_path(:quad=>@random_top.quadrant,:category=>@random_top.clothing_category,:pastid => @random_top.id, :userid=>@random_top.user_id,:occ =>@random_top.occasion),id:"top",remote: true%>
      <%end%>
      <%if !@random_top2.nil? && @random_top2.photo.attached? %>
      <%= link_to image_tag(@random_top2.photo, width: 260,height: 260),generate_again_path(:quad=>@random_top2.quadrant,:category=>@random_top2.clothing_category,:pastid => @random_top2.id, :userid=>@random_top2.user_id,:occ =>@random_top2.occasion),id:"top2",remote: true%>
      <%end%>
      </div>
      <div>
      <%if !@random_bottom.nil? && @random_bottom.photo.attached? %>
      <%= link_to image_tag(@random_bottom.photo, width: 260,height: 330),generate_again_path(:quad=>@random_bottom.quadrant,:category=>@random_bottom.clothing_category,:pastid => @random_bottom.id, :userid=>@random_bottom.user_id,:occ =>@random_bottom.occasion),id:"bottom",remote: true%>
      <%end%>   
      </div>
      <div>
      <%if !@random_socks.nil? && @random_socks.photo.attached? %>
      <%= link_to image_tag(@random_socks.photo, width: 260,height: 260),generate_again_path(:quad=>@random_socks.quadrant,:category=>@random_socks.clothing_category,:pastid => @random_socks.id, :userid=>@random_socks.user_id,:occ =>@random_socks.occasion),id:"socks",remote: true%>
      <%end%> 
      <%if !@random_shoes.nil? && @random_shoes.photo.attached? %>
      <%= link_to image_tag(@random_shoes.photo, width: 260,height: 260),generate_again_path(:quad=>@random_shoes.quadrant,:category=>@random_shoes.clothing_category,:pastid => @random_shoes.id, :userid=>@random_shoes.user_id,:occ =>@random_shoes.occasion),id:"shoes",remote: true%>
      <%end%> 
      </div>
    </div>
  </div>
</div>

app/views/users/generate_again.js.erb
<% if !@random_top.nil?%>
$("#top").html('<%= j link_to image_tag(@random_top.photo, width: 260,height: 260, id:"top"),generate_again_path(:quad=>@random_top.quadrant,:category=>@random_top.clothing_category,:pastid => @random_top.id, :userid=>@random_top.user_id,:occ =>@random_top.occasion), remote: true %>') ;
<% elsif !@random_top2.nil?%>
$("#top2").html('<%= j link_to image_tag(@random_top2.photo, width: 260,height: 260, id:"top2"),generate_again_path(:quad=>@random_top2.quadrant,:category=>@random_top2.clothing_category,:pastid => @random_top2.id, :userid=>@random_top2.user_id,:occ =>@random_top2.occasion), remote: true %>') ;
<% elsif !@random_bottom.nil?%>
$("#bottom").html('<%= j link_to image_tag(@random_bottom.photo, width: 260,height: 330, id:"bottom"),generate_again_path(:quad=>@random_bottom.quadrant,:category=>@random_bottom.clothing_category,:pastid => @random_bottom.id, :userid=>@random_bottom.user_id,:occ =>@random_bottom.occasion), remote: true %>') ;
<% elsif !@random_socks.nil?%>
$("#socks").html('<%= j link_to image_tag(@random_socks.photo, width: 260,height: 260, id:"socks"),generate_again_path(:quad=>@random_socks.quadrant,:category=>@random_socks.clothing_category,:pastid => @random_socks.id, :userid=>@random_socks.user_id,:occ =>@random_socks.occasion), remote: true %>') ;
<% elsif !@random_shoes.nil?%>
$("#shoes").html('<%= j link_to image_tag(@random_shoes.photo, width: 260,height: 260, id:"shoes"),generate_again_path(:quad=>@random_shoes.quadrant,:category=>@random_shoes.clothing_category,:pastid => @random_shoes.id, :userid=>@random_shoes.user_id,:occ =>@random_shoes.occasion), remote: true %>') ;
<% elsif !@random_accessory.nil?%>
$("#accessory").html('<%= j link_to image_tag(@random_accessory.photo, width: 260,height: 260, id:"accessory"),generate_again_path(:quad=>@random_accessory.quadrant,:category=>@random_accessory.clothing_category,:pastid => @random_accessory.id, :userid=>@random_accessory.user_id,:occ =>@random_accessory.occasion), remote: true %>') ;
<%end%>

app/views/users/index.html.erb
<!--Testing purposes-->
<p id="notice"><%= notice %></p>

<div class="d-flex justify-content-center">
<h1 style="text-align:center;">Users</h1>
</div>


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= button_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/laundry.html.erb

<!DOCTYPE html>
<html>

<header>
	<link href="https://fonts.googleapis.com/css2?family=Indie+Flower&family=Zen+Kurenaido&display=swap" rel="stylesheet">
	<%= render "layouts/header" %>
	<p id="notice"><%= notice %></p>
</header>
<body>
	<div style="text-align: center">
		<h1 class="center">These clothes need washing!</h1>
		<br>
		<div>
			<h2 class="text-with-line"><span>Tops</span></h2>
			<%= render 'dirty_clothes', quad: "Top" %>
			<h2 class="text-with-line"><span>Bottoms</span></h2>
			<%= render 'dirty_clothes', quad: "Bottom" %>
			<h2 class="text-with-line"><span>Socks</span></h2>
			<%= render 'dirty_clothes', quad: "Socks" %>
		</div>
	</div>
	<%= button_to "Wash clothes",wash_path(:user_id => session[:user_id]),:method => :patch, class: "btn green-btn divide"%>
</body>
</html>

app/views/users/new.html.erb
<head>
<% provide(:title, "Sign Up") %>
<link href="https://fonts.googleapis.com/css2?family=Indie+Flower&family=Zen+Kurenaido&display=swap" rel="stylesheet">
</head>
<%= render "layouts/header" %>
<div class="row justify-content-center" style="margin: 80px 20px 10px 30px;">  
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-with-line" style="padding-bottom: 10px;">Sign up</h1>
      <%= form_with(model: @user, local: true) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
        <%= f.submit "Register", class: "btn green-btn" %>
      <% end %>             
  </div>      
</div> 

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<header>
<link href="https://fonts.googleapis.com/css2?family=Indie+Flower&family=Zen+Kurenaido&display=swap" rel="stylesheet">
<%= render "layouts/header" %>
<p id="notice"><%= notice %></p>
</header>
<body>
<div style="text-align: center">
<h1 class="center">
  <%= @user.name%>'s closet
</h1>
<br>
<div>
<h2 class="text-with-line"><span>Tops</span></h2>
<%= render 'my_partial', quad: "Top" %>
<h2 class="text-with-line"><span>Bottoms</span></h2>
<%= render 'my_partial', quad: "Bottom" %>
<h2 class="text-with-line"><span>Socks</span></h2>
<%= render 'my_partial', quad: "Socks" %>
<h2 class="text-with-line"><span>Shoes</span></h2>
<%= render 'my_partial', quad: "Shoes" %>
<h2 class="text-with-line"><span>Accessories</span></h2>
<%= render 'my_partial', quad: "Accessory" %>
</div>
</div>
</body>
</html>