config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  root 'static_pages#home'
  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :clothes
  resources :users
  # root 'application#welcome'
  get '/signup', to: 'users#new'
  get '/uploadclothes', to: 'clothes#new'
  get '/generate', to: 'users#generate'
  get '/generate_again', to: 'users#generate_again', as: :generate_again
  get '/closet', to: 'sessions#show'
  get '/laundry', to: 'users#laundry'
  patch '/ootd', to: 'users#ootd'
  patch '/wash', to: 'users#wash'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/clothe.rb
class Clothe < ApplicationRecord
  has_one_attached :photo
  belongs_to :user
end

app/controllers/clothes_controller.rb
require './app/services/imagetag.rb'
require './app/services/clothingcolor.rb'
class ClothesController < ApplicationController
  before_action :set_clothe, only: %i[show edit update destroy]

  # GET /clothes or /clothes.json
  def index
    @clothes = Clothe.all
  end

  # GET /clothes/1 or /clothes/1.json
  def show; end

  # GET /clothes/new
  def new
    @clothe = Clothe.new(user_id: params[:user_id])
  end

  # GET /clothes/1/edit
  def edit; end

  # POST /clothes or /clothes.json
  def create
    @clothe = Clothe.new(clothe_params)
    @clothe.clean = true
    respond_to do |format|
      if @clothe.save
        image_url = @clothe.photo.url
        image_url = image_url[0,image_url.index('?response')]

        tags_api = ImageTag.new(image_url)
        quad, category, oc = tags_api.get_tags() 
        @clothe.update(quadrant:quad) 
        @clothe.update(clothing_category: category)
        @clothe.update(occasion:oc)

        color_api = ClothingColor.new(image_url)
        color = color_api.get_clothing_color()
        @clothe.update(color: color)

        format.html { redirect_to edit_clothe_path(@clothe) }
        format.json { render :show, status: :created, location: @clothe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @clothe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clothes/1 or /clothes/1.json
  def update
    respond_to do |format|
      if @clothe.update(clothe_params)
        format.html { redirect_to user_path(@clothe.user_id) }
        format.json { render :show, status: :ok, location: @clothe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @clothe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clothes/1 or /clothes/1.json
  def destroy
    user_id = @clothe.user_id
    @clothe.destroy
    respond_to do |format|
      format.html { redirect_to user_path(user_id) }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_clothe
    @clothe = Clothe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def clothe_params
    params.require(:clothe).permit(:user_id, :quadrant, :clothing_category, :color, :occasion, :photo)
  end
end

app/helpers/clothes_helper.rb
module ClothesHelper
end

app/views/clothes/_form.html.erb
<div style="text-align:center;">
<%= form_with(model: clothe) do |form| %>
  <% if clothe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(clothe.errors.count, "error") %> prohibited this clothe from being saved:</h2>

      <ul>
        <% clothe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.hidden_field :user_id%>
  </div>

  <div class="field">
    <%= form.label :quadrant, "Category"  %>
    <%= form.select :quadrant, ["Top","Bottom","Socks","Shoes","Accessory"],selected:@clothe.quadrant, class: 'form-select form-select-sm w-25', :required => true %>
  </div>

  <div class="field">
    <%= form.label :clothing_category ,"Style" %>
    <%= form.select :clothing_category, ["T-Shirt","Hoodie","Longsleeve","Button-down","Winter-Coat","Fall/Spring-Jacket","Dress","Jeans","Pants","Shorts","Skirt","Leggings","Sweatpants","Sneakers","Dress-Shoes","Sandals","Boots","Socks","Hat","Gloves","Scarf"], selected:@clothe.clothing_category, class: 'form-select form-select-sm w-25', :required => true %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.color_field :color,value:@clothe.color, class: 'upload-form h-100 w-50', :required => true %>
  </div>

  <div class="field">
    <%= form.label :occasion %>
    <%= form.select :occasion, ["Casual","Business-Casual"],select:@clothe.occasion, class: 'form-select form-select-sm w-25', :required => true %>
  </div>
<div class="field">
  </div>
    <div class="actions">
      <%= form.submit "Save" ,class: "btn green-btn" %>
    </div>
<% end %>

</div>

app/views/clothes/edit.html.erb
<head>
<% provide(:title, "Edit Clothes") %>
<link href="https://fonts.googleapis.com/css2?family=Indie+Flower&family=Zen+Kurenaido&display=swap" rel="stylesheet">
</head>

<%= render "layouts/header" %>
<div style="display: flex; justify-content:center;">
<h1 style="margin-top: 30px;">Edit Clothes</h1>
</div>
<div id = "begin-exploring" class="row justify-content-center" style="margin: 20px 20px 10px 30px;">  
  <div class="card-div col-md-6 col-md-offset-3" align="center">
    <%= image_tag(@clothe.photo, style:'border-radius: 50%; height:350px; width: 350px') if @clothe.photo.attached? %>
  </div>

  <div class="col-md-6 col-md-offset-3">
    <%= render 'form', clothe: @clothe %>
    <%= button_to 'Remove from closet', @clothe, method: :delete, data: { confirm: 'Are you sure?' } ,class: "btn green-btn" %>
  </div>
</div>


app/views/clothes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clothes</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Quadrant</th>
      <th>Clothing category</th>
      <th>Color</th>
      <th>Occasion</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clothes.each do |clothe| %>
      <tr>
        <td><%= clothe.user_id %></td>
        <td><%= clothe.quadrant %></td>
        <td><%= clothe.clothing_category %></td>
        <td><%= clothe.color %></td>
        <td><%= clothe.occasion %></td>
        <td><%= image_tag(clothe.photo, width: 200) if clothe.photo.attached? %></td>
        <td><%= link_to 'Show', clothe %></td>
        <td><%= link_to 'Edit', edit_clothe_path(clothe) %></td>
        <td><%= button_to 'Destroy', clothe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Clothe', new_clothe_path %>

app/views/clothes/new.html.erb
<head>
<% provide(:title, "Upload Clothes") %>
<link href="https://fonts.googleapis.com/css2?family=Indie+Flower&family=Zen+Kurenaido&display=swap" rel="stylesheet">
</head>

<%= render "layouts/header" %>


<div class="container-form" style="margin: auto auto; padding: 30px; text-align:center;">
    <h1>Upload your clothes here!</h1>
    <div>
        <div class="clothing-carousel"> 
            <input type="radio" name="position" checked />
            <input type="radio" name="position" />
            <input type="radio" name="position" />
            <input type="radio" name="position" />
            <input type="radio" name="position" />
            <main id="carousel">
                <div class="item-card"></div>
                <div class="item-card"></div>
                <div class="item-card"></div>
                <div class="item-card"></div>
                <div class="item-card"></div>
            <main>
        </div>
    </div>
    <div>
        <%= form_with(model: @clothe, local: true) do |f| %>
            <%= f.hidden_field :user_id %>
            <%= f.label :photo%>
            <div>
                <%= f.file_field :photo, :required => true, style: "width:250px"%>
            </div>
            <%= f.submit "Upload", class: "btn green-btn w-25" %>
        <% end %>
    </div>
</div>

<div>
</div>

app/views/clothes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @clothe.user_id %>
</p>

<p>
  <strong>Quadrant:</strong>
  <%= @clothe.quadrant %>
</p>

<p>
  <strong>Clothing category:</strong>
  <%= @clothe.clothing_category %>
</p>

<p>
  <strong>Color:</strong>
  <%= @clothe.color %>
</p>

<p>
  <strong>Occasion:</strong>
  <%= @clothe.occasion %>
</p>
<%= image_tag(@clothe.photo, width: 200) if @clothe.photo.attached? %>
<%= link_to 'Edit', edit_clothe_path(@clothe) %> |
<%= link_to 'Back', 'javascript:history.go(-2);' %>