config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  root 'static_pages#home'
  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :clothes
  resources :users
  # root 'application#welcome'
  get '/signup', to: 'users#new'
  get '/uploadclothes', to: 'clothes#new'
  get '/generate', to: 'users#generate'
  get '/generate_again', to: 'users#generate_again', as: :generate_again
  get '/closet', to: 'sessions#show'
  get '/laundry', to: 'users#laundry'
  patch '/ootd', to: 'users#ootd'
  patch '/wash', to: 'users#wash'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<script src="https://kit.fontawesome.com/925da18a86.js" crossorigin="anonymous"></script>
<body class="gradient-custom"style="margin:0px; font-family: 'Zen Kurenaido', sans-serif; color: white;">
<script type="text/javascript">
  $(function() {
   $('.navbar .nav > li > a').click(function(e){
       $('.navbar .nav > li.active').removeClass('active')
       $(this).parent('div').addClass('active')
    });
  });
</script>

<!-- Navbar -->
        <% if not !session[:user_id].nil? %>
            <nav class="navbar sticky-top navbar-expand-sm navbar-custom ">
                <div class="container">
                    <div class="navbar-brand">
                        <%= link_to image_tag('logo.png', style: 'height:15%; width: 50%;', alt: "Style Me! Logo"), root_path %>
                    </div>
                    
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse d-flex justify-content-end" id="navbarNav">
                        <ul class = "navbar-nav">
                            <li class="nav-item unboxed-button <%='active' if current_page?(login_path) %>">
                                <%= link_to "Log In", login_path%>
                            </li>
                            <li class="nav-item unboxed-button <%='active' if current_page?(signup_path) %>">
                                <i class="fas fa-user-plus "></i>
                                <%= link_to "Sign up", signup_path%>
                                </i>
                            </li>
                        </ul>
                    </div>
                </div>
            <% end %>
            <% if !session[:user_id].nil? %>
            <nav class="navbar sticky-top navbar-expand-sm navbar-custom ">
                <div class="container">
                    <div class="navbar-brand">
                        <%= link_to image_tag('logo.png', style: 'height:15%; width: 50%;', alt: "Style Me! Logo"), "/users/#{session[:user_id]}" %>
                    </div>
                    
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse d-flex justify-content-end" id="navbarNav">
                        <ul class = "navbar-nav">
                            <li class="nav-item unboxed-button <%='active' if current_page?(laundry_path(:user_id => session[:user_id])) %>">
                                <%= link_to "Laundry", laundry_path(:user_id => session[:user_id])%>
                            </li>
                            <li class="nav-item unboxed-button <%='active' if current_page?(uploadclothes_path(:user_id => session[:user_id])) %>">
                                <%= link_to "Upload Clothes", uploadclothes_path(:user_id => current_user.id)%>
                            </li>
                            <li class="nav-item unboxed-button <%='active' if current_page?(generate_path(:user_id => session[:user_id])) %>">
                                <%= link_to "Generate Outfit", generate_path(:user_id => current_user.id)%>
                            </li>
                            <li class="nav-item unboxed-button <%='active' if current_page?("/users/#{session[:user_id]}")%>">
                                <%= link_to "My Closet", "/users/#{session[:user_id]}"%>
                            </li>
                            <li class="nav-item unboxed-button" role="button">
                            <i class="fas fa-sign-out-alt">
                                <%= link_to "Log Out", logout_path, method: :delete%>
                            </i>
                            </li>
                        </ul>
                    </div>
                </div>
                    </div>
                </div>
            <% end %>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OutfitPlanner</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>
 